#!/usr/bin/env node
/**
 * Build step: regenerate the per-object field/picklist `$defs` in
 * `schema/quote-graph.schema.json` from SObject describe metadata, so the base
 * graph contract can't drift from the org.
 *
 *   describe(Quote, QuoteLineItem, …)  ->  schema/quote-graph.schema.json  ($defs.*Fields)
 *
 * The set of objects is driven by the `node.objectApiName` enum already in the
 * schema — the schema is the single source of truth, there is no second list to
 * keep in sync.
 *
 * Describe source:
 *   --target-org <alias>   pull live via `sf sobject describe` and refresh the
 *                          checked-in fixtures under scripts/describe/.
 *   (default / offline)    read scripts/describe/<Object>.describe.json, so the
 *                          build runs without an org (CI, sandboxes).
 *
 * For each object we emit `<camelCaseObject>Fields`: a property per
 * createable-or-updateable, non-calculated, non-deprecated field, with picklist
 * enums from the live (active) values and `required` for fields that must be
 * supplied by the caller. The generated defs are wired into `node` via a
 * conditional on `objectApiName`, so authoring tools and the LLM see the real
 * constraints (Apex runtime validation is unchanged).
 *
 * Output is deterministic (sorted keys) so re-runs produce clean diffs.
 *
 * Usage:
 *   node scripts/build-schema.mjs                     # offline, from fixtures
 *   node scripts/build-schema.mjs --target-org myOrg  # live, refreshes fixtures
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const schemaPath = join(root, 'schema', 'quote-graph.schema.json');
const fixturesDir = join(root, 'scripts', 'describe');

const GENERATED_MARKER =
  'GENERATED by scripts/build-schema.mjs from SObject describe — do not hand-edit. Run `node scripts/build-schema.mjs` to refresh.';

// --- args -------------------------------------------------------------------
const argv = process.argv.slice(2);
const orgFlag = argv.indexOf('--target-org');
const targetOrg = orgFlag !== -1 ? argv[orgFlag + 1] : null;

// --- describe source --------------------------------------------------------
/** Pull describe live and refresh the checked-in fixture. */
function describeFromOrg(object) {
  const out = execFileSync(
    'sf',
    ['sobject', 'describe', '--sobject', object, '--target-org', targetOrg, '--json'],
    { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
  );
  if (!existsSync(fixturesDir)) mkdirSync(fixturesDir, { recursive: true });
  // Re-serialize so the fixture is stable/pretty rather than one long CLI line.
  const parsed = JSON.parse(out);
  writeFileSync(
    join(fixturesDir, `${object}.describe.json`),
    JSON.stringify(parsed, null, 2) + '\n',
  );
  return parsed;
}

/** Read the checked-in fixture (offline default). */
function describeFromFixture(object) {
  const path = join(fixturesDir, `${object}.describe.json`);
  if (!existsSync(path)) {
    throw new Error(
      `No describe for ${object}: ${path} is missing. ` +
        `Run with --target-org <alias> to generate it from a live org.`,
    );
  }
  return JSON.parse(readFileSync(path, 'utf8'));
}

function describeOf(object) {
  const raw = targetOrg ? describeFromOrg(object) : describeFromFixture(object);
  // `sf ... --json` wraps the describe in { status, result }; fixtures match.
  const result = raw && raw.result ? raw.result : raw;
  if (!result || !Array.isArray(result.fields)) {
    throw new Error(`describe for ${object} has no fields array`);
  }
  return result;
}

// --- field describe -> JSON Schema property ---------------------------------
const TEXTUAL = new Set([
  'string', 'textarea', 'phone', 'email', 'url', 'encryptedstring', 'combobox', 'reference', 'id',
]);

function activePicklistValues(field) {
  return (field.picklistValues || [])
    .filter((p) => p.active !== false)
    .map((p) => p.value);
}

/** True if the field is something a caller can write at all. */
function isWritable(field) {
  if (field.calculated || field.deprecatedAndHidden) return false;
  if (field.type === 'address' || field.type === 'location') return false; // compound
  return Boolean(field.createable || field.updateable);
}

/**
 * True if the caller MUST supply the field on create. Reference (FK) fields are
 * excluded even when describe marks them non-nillable: parent FKs are back-filled
 * by the engine from `parentAlias`, and other lookups (e.g. PricebookEntryId) are
 * filled by reference resolution — demanding them on the authoring surface would
 * be wrong.
 */
function isRequired(field) {
  if (field.type === 'reference') return false;
  return field.createable === true && field.nillable === false && field.defaultedOnCreate !== true;
}

function propertyFor(field) {
  const prop = {};
  switch (field.type) {
    case 'picklist':
    case 'multipicklist': {
      prop.type = 'string';
      const values = activePicklistValues(field);
      if (values.length) prop.enum = values;
      break;
    }
    case 'boolean':
      prop.type = 'boolean';
      break;
    case 'int':
      prop.type = 'integer';
      break;
    case 'double':
    case 'currency':
    case 'percent':
      prop.type = 'number';
      break;
    case 'date':
      prop.type = 'string';
      prop.format = 'date';
      break;
    case 'datetime':
      prop.type = 'string';
      prop.format = 'date-time';
      break;
    case 'email':
      prop.type = 'string';
      prop.format = 'email';
      break;
    case 'url':
      prop.type = 'string';
      prop.format = 'uri';
      break;
    default:
      prop.type = 'string';
  }
  if (prop.type === 'string' && TEXTUAL.has(field.type) && field.length > 0) {
    prop.maxLength = field.length;
  }
  return prop;
}

/** Quote -> quoteFields, OpportunityLineItem -> opportunityLineItemFields. */
function defNameFor(object) {
  return object.charAt(0).toLowerCase() + object.slice(1) + 'Fields';
}

function fieldsDefFor(object, describe) {
  const writable = describe.fields.filter(isWritable);
  const properties = {};
  for (const f of writable.sort((a, b) => a.name.localeCompare(b.name))) {
    properties[f.name] = propertyFor(f);
  }
  const required = writable
    .filter(isRequired)
    .map((f) => f.name)
    .sort((a, b) => a.localeCompare(b));

  const def = {
    type: 'object',
    description: `${GENERATED_MARKER} Source: describe('${object}').`,
    additionalProperties: false,
    properties,
  };
  if (required.length) def.required = required;
  return def;
}

// --- splice generated defs into the schema ----------------------------------
const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));

const objects = schema?.$defs?.node?.properties?.objectApiName?.enum;
if (!Array.isArray(objects) || objects.length === 0) {
  throw new Error('schema $defs.node.properties.objectApiName.enum is missing — nothing to generate');
}

// 1. Rebuild $defs: keep hand-authored entries, drop previously-generated ones.
const handAuthored = {};
for (const [key, val] of Object.entries(schema.$defs)) {
  if (key.endsWith('Fields')) continue; // generated
  if (key === '_comment_generated' || key === '_generated') continue; // old markers
  handAuthored[key] = val;
}

const generatedDefs = {};
const defNameByObject = {};
for (const object of objects) {
  const name = defNameFor(object);
  defNameByObject[object] = name;
  generatedDefs[name] = fieldsDefFor(object, describeOf(object));
}

schema.$defs = {
  ...handAuthored,
  _generated: GENERATED_MARKER,
  ...Object.fromEntries(Object.keys(generatedDefs).sort().map((k) => [k, generatedDefs[k]])),
};

// 2. Wire each object's fields def into node via a conditional on objectApiName.
//    Keep hand-authored conditionals (those without a #/$defs/*Fields fields ref).
const node = schema.$defs.node;
const isGeneratedConditional = (entry) => {
  const ref = entry?.then?.properties?.fields?.$ref;
  return typeof ref === 'string' && ref.startsWith('#/$defs/') && ref.endsWith('Fields');
};
const baseAllOf = (node.allOf || []).filter((e) => !isGeneratedConditional(e));
const fieldConditionals = objects.map((object) => ({
  if: { properties: { objectApiName: { const: object } } },
  then: { properties: { fields: { $ref: `#/$defs/${defNameByObject[object]}` } } },
}));
node.allOf = [...baseAllOf, ...fieldConditionals];

// 3. Write back deterministically.
writeFileSync(schemaPath, JSON.stringify(schema, null, 2) + '\n');

const total = Object.keys(generatedDefs).length;
console.log(
  `Generated ${total} field def(s) from ${targetOrg ? `org "${targetOrg}"` : 'fixtures'}: ` +
    objects.map((o) => defNameByObject[o]).join(', '),
);
for (const object of objects) {
  const def = generatedDefs[defNameByObject[object]];
  console.log(
    `  ${object}: ${Object.keys(def.properties).length} field(s)` +
      (def.required ? `, ${def.required.length} required` : ''),
  );
}
